s3_base_path: "s3_base_path"

# store lgos (optional)
logs_dir: "./logs"

# temporarily store zip files for uploading
working_dir: ./tmp

# max size for each zip file
max_zip_size: 5000 # in MB
notify_script: 'echo "%icon% %operation% - %status% | %message%"'
tasks:
  - id: photos
    dir: "./test-files"

    # which storage class to use for your backup zips. one of STANDARD | INTELLIGENT_TIERING | STANDARD_IA  | ONEZONE_IA | GLACIER | DEEP_ARCHIVE
    # Default is DEEP_ARCHIVE
    # DB is always stored in STANDARD
    storage_class: "STANDARD"
    encryption_key: PASasdSWORD
    # exclude: ["**/nukAibOVlg/**/*", "**/.DS_Store"]

  - id: videos
    dir: "./test-videos"
    storage_class: "STANDARD"
